### PR TITLE
CMGWT-12: update geomajas codemirror gwt documenation url

### PR DESCRIPTION
**Pull request by janvenstermans**
example at http://dev.geomajas.org/geomajas-project-codemirror-gwt-example-CMGWT-12/

### CODE REVIEW

**Comment by janvenstermans** [comment]
Jan Venstermans: +1

**Comment by jandm** [comment]
+1: binding

**Comment by oliverm-be** [comment]
Oliver May: +1 (binding)

**Comment by janvenstermans** [comment]
Bugfix vote count:
Jan De Moerloose: +1: binding
Oliver May: +1 (binding)

Jan Venstermans: +1

Vote successful

**Pull request merged**
